---
title: "2018-10-03"
output: html_notebook
---

```{r}
lubridate::ymd("2017/01/31")
```

```{r}
library(lubridate)
d <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="month")#sequence，產生具有順序的東西,by以多少為單位
e <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="quarter")
f <- seq(ymd("2001-01-01"),ymd("2018-09-01"),by="year")
```
str_sub(string,start = 1L,end = -1L)start and end must be an int
```{r}
hw <-"Hadley Wickham"
library(stringr)
str_sub(hw,1,6)
str_sub(hw,end = 6)
str_sub(hw,8,14)
```
```{r}
library(readr)
library(stringr)
studentID <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/studentID.csv")
```
```{r}
str_sub(studentID$學號,5,6) ->aa
table(aa)
```

```{r}
str_c(letters,LETTERS)
str_c(letters,LETTERS,sep="-")
str_c("lowercase: ", letters, ", capital: ", LETTERS)
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
```
```{r}
githubData[c(2,3,4),] -> sampleGithub#[c(2,3,4),]代表矩陣
str_c(sampleGithub$`GitHub username`,
      "/",
      sampleGithub$`GitHub repo name`)
str_c("https://github.com/",
      sampleGithub$`GitHub username`,
      "/",
      sampleGithub$`GitHub repo name`)
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
```
```{r}
fruits <- c(
  "apples and oranges and pears and bananas",
  "pineapples and mangos and guavas"
)
str_split_fixed(fruits, " and ", 3)#形成矩陣
str_split_fixed(fruits, " and ", 4)
```

